version: '3'
services:
  digitalize-client:
    build:
      context: ./client
    ports:
      - '3000:3000'
    container_name: digitalize-client

  digitalize-server:
    build:
      context: ./server
    ports:
      - '8000:8000'
    container_name: digitalize-server